import type { OrderItem } from '../types/order';

export const INITIAL_MOCK_ORDERS: OrderItem[] = [
  {
    id: 'ORD-140306-101',
    orderNumber: 'پاکشو-۱۰۱۰۱',
    serviceId: 'home_unit_cleaning',
    serviceTitle: 'نظافت داخل منزل / واحد',
    serviceSubtitle: 'خدمت ساعتی، حداقل ۴ ساعت',
    pricingType: 'hourly',
    status: 'IN_PROGRESS',
    paymentStatus: 'PAID',
    paymentMethod: 'ONLINE',
    date: {
      dateString: '1403-06-16',
      dayOfWeek: 'جمعه',
      dayOfMonth: 16,
      monthName: 'شهریور ۱۴۰۳',
      isToday: true,
    },
    timeSlot: {
      id: 'morning-2',
      startTime: '10:00',
      endTime: '12:00',
      label: 'صبح',
      period: 'MORNING',
      isAvailable: true,
    },
    durationHours: 4,
    genderPreference: 'FEMALE',
    serviceOptions: {
      detergent: true,
    },
    recurringFrequency: 'WEEKLY',
    customerTier: 'GOLD',
    address: {
      district: 'سعادت‌آباد',
      fullAddress: 'بلوار سرو غربی، خیابان صدف، پلاک ۲۴، واحد ۳',
      plaque: '۲۴',
      unit: '۳',
      floor: '۲',
      hasElevator: true,
      contactPhone: '۰۹۱۲۳۴۵۶۷۸۹',
      recipientName: 'علی رضایی',
      coordinates: { latitude: 35.7794, longitude: 51.3756 },
    },
    pricing: {
      subtotal: 650000,
      earlyBirdDiscountRate: 0,
      earlyBirdDiscountAmount: 0,
      tierDiscountRate: 0.05,
      tierDiscountAmount: 32500,
      recurringDiscountRate: 0.05,
      recurringDiscountAmount: 0,
      discountRate: 0.05,
      discountAmount: 32500,
      recurringDiscountDeferred: true,
      total: 617500,
    },
    cleaner: {
      id: 'CLN-801',
      name: 'خانم مریم مرادی',
      phone: '۰۹۳۵۱۱۱۴۴۵۵',
      rating: 4.9,
      completedJobsCount: 142,
    },
    timeline: [
      { step: 'SUBMITTED', title: 'ثبت سفارش', timestamp: '۰۹:۱۵', isCompleted: true, isCurrent: false, description: 'سفارش در سامانه پاکشو با موفقیت ثبت شد.' },
      { step: 'CONFIRMED', title: 'تأیید سفارش', timestamp: '۰۹:۲۵', isCompleted: true, isCurrent: false, description: 'هماهنگی و اعتبارسنجی اولیه انجام شد.' },
      { step: 'ASSIGNED', title: 'تخصیص متخصص', timestamp: '۰۹:۳۵', isCompleted: true, isCurrent: false, description: 'خانم مریم مرادی به عنوان متخصص اعزام شد.' },
      { step: 'STARTED', title: 'شروع نظافت', timestamp: '۱۰:۰۵', isCompleted: true, isCurrent: true, description: 'متخصص در محل حاضر و کار آغاز شد.' },
      { step: 'FINISHED', title: 'پایان کار و رضایت‌سنجی', timestamp: '۱۴:۰۰ (تخمینی)', isCompleted: false, isCurrent: false },
    ],
    notes: 'لطفاً شستشوی پنجره‌های سالن پذیرایی با دقت انجام شود.',
    createdAt: '2026-09-06T09:15:00.000Z',
    updatedAt: '2026-09-06T10:05:00.000Z',
  },
  {
    id: 'ORD-140306-102',
    orderNumber: 'پاکشو-۱۰۱۰۲',
    serviceId: 'sofa_carpet_washing',
    serviceTitle: 'مبل‌شویی و فرش‌شویی در محل',
    serviceSubtitle: 'قیمت‌گذاری بر اساس تعداد نشیمن و تشک',
    pricingType: 'count_based',
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    paymentMethod: 'ONLINE',
    date: {
      dateString: '1403-06-25',
      dayOfWeek: 'یکشنبه',
      dayOfMonth: 25,
      monthName: 'شهریور ۱۴۰۳',
      isToday: false,
    },
    timeSlot: {
      id: 'afternoon-1',
      startTime: '14:00',
      endTime: '16:00',
      label: 'ظهر',
      period: 'AFTERNOON',
      isAvailable: true,
    },
    durationHours: 3,
    genderPreference: 'NO_PREFERENCE',
    serviceOptions: {
      sofaSeats: '۷ نفره',
      mattresses: 1,
    },
    recurringFrequency: 'ONE_TIME',
    customerTier: 'GOLD',
    address: {
      district: 'شهرک غرب',
      fullAddress: 'بلوار ایران‌زمین، خیابان مهستان، پلاک ۱۲، واحد ۴',
      plaque: '۱۲',
      unit: '۴',
      floor: '۳',
      hasElevator: true,
      contactPhone: '۰۹۱۲۳۴۵۶۷۸۹',
      recipientName: 'علی رضایی',
      coordinates: { latitude: 35.7533, longitude: 51.3654 },
    },
    pricing: {
      subtotal: 450000,
      earlyBirdDiscountRate: 0.05,
      earlyBirdDiscountAmount: 22500,
      tierDiscountRate: 0.05,
      tierDiscountAmount: 22500,
      recurringDiscountRate: 0,
      recurringDiscountAmount: 0,
      discountRate: 0.1,
      discountAmount: 45000,
      recurringDiscountDeferred: false,
      total: 405000,
    },
    cleaner: {
      id: 'CLN-604',
      name: 'آقای رضا کریمی',
      phone: '۰۹۱۹۳۳۳۷۷۸۸',
      rating: 4.8,
      completedJobsCount: 98,
    },
    timeline: [
      { step: 'SUBMITTED', title: 'ثبت سفارش', timestamp: '۱۱:۲۰', isCompleted: true, isCurrent: false, description: 'سفارش ثبت و پرداخت آنلاین تایید گردید.' },
      { step: 'CONFIRMED', title: 'تأیید سفارش', timestamp: '۱۱:۳۰', isCompleted: true, isCurrent: true, description: 'زمان‌بندی سرویس در تقویم رزرو ثبت شد.' },
      { step: 'ASSIGNED', title: 'تخصیص متخصص', timestamp: 'در انتظار اعزام', isCompleted: false, isCurrent: false },
      { step: 'STARTED', title: 'شروع نظافت', timestamp: '۲۵ شهریور', isCompleted: false, isCurrent: false },
      { step: 'FINISHED', title: 'پایان کار', timestamp: '---', isCompleted: false, isCurrent: false },
    ],
    notes: 'یک دست مبل راحتی مخمل ۷ نفره و یک عدد تشک دونفره.',
    createdAt: '2026-09-06T11:20:00.000Z',
    updatedAt: '2026-09-06T11:30:00.000Z',
  },
  {
    id: 'ORD-140306-098',
    orderNumber: 'پاکشو-۱۰۰۹۸',
    serviceId: 'office_company_cleaning',
    serviceTitle: 'نظافت دفاتر اداری و شرکت‌ها',
    serviceSubtitle: 'خدمت ساعتی، حداقل ۴ ساعت',
    pricingType: 'hourly',
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    paymentMethod: 'ONLINE',
    date: {
      dateString: '1403-06-10',
      dayOfWeek: 'شنبه',
      dayOfMonth: 10,
      monthName: 'شهریور ۱۴۰۳',
      isToday: false,
    },
    timeSlot: {
      id: 'morning-1',
      startTime: '08:00',
      endTime: '10:00',
      label: 'صبح زود',
      period: 'MORNING',
      isAvailable: true,
    },
    durationHours: 6,
    genderPreference: 'MALE',
    serviceOptions: {
      hours: 6,
    },
    recurringFrequency: 'BIWEEKLY',
    customerTier: 'GOLD',
    address: {
      district: 'ونک',
      fullAddress: 'میدان شیخ بهایی، برج صدف، طبقه ۶، واحد ۶۲',
      plaque: '۴',
      unit: '۶۲',
      floor: '۶',
      hasElevator: true,
      contactPhone: '۰۹۱۲۳۴۵۶۷۸۹',
      recipientName: 'شرکت فناوران اطلس',
      coordinates: { latitude: 35.7582, longitude: 51.3984 },
    },
    pricing: {
      subtotal: 1080000,
      earlyBirdDiscountRate: 0,
      earlyBirdDiscountAmount: 0,
      tierDiscountRate: 0.05,
      tierDiscountAmount: 54000,
      recurringDiscountRate: 0.1,
      recurringDiscountAmount: 108000,
      discountRate: 0.15,
      discountAmount: 162000,
      recurringDiscountDeferred: false,
      total: 918000,
    },
    cleaner: {
      id: 'CLN-512',
      name: 'آقای صادق حسینی',
      phone: '۰۹۱۲۹۹۹۳۳۲۲',
      rating: 4.95,
      completedJobsCount: 215,
    },
    timeline: [
      { step: 'SUBMITTED', title: 'ثبت سفارش', timestamp: '۱۰ شهریور ۰۸:۰۰', isCompleted: true, isCurrent: false },
      { step: 'CONFIRMED', title: 'تأیید سفارش', timestamp: '۱۰ شهریور ۰۸:۱۰', isCompleted: true, isCurrent: false },
      { step: 'ASSIGNED', title: 'تخصیص متخصص', timestamp: '۱۰ شهریور ۰۸:۱۵', isCompleted: true, isCurrent: false },
      { step: 'STARTED', title: 'شروع نظافت', timestamp: '۱۰ شهریور ۰۸:۳۰', isCompleted: true, isCurrent: false },
      { step: 'FINISHED', title: 'پایان کار و تسویه', timestamp: '۱۰ شهریور ۱۴:۳۰', isCompleted: true, isCurrent: true },
    ],
    ratings: {
      customerRating: 5,
      customerComment: 'بسیار با نظم، وقت‌شناس و حرفه‌ای بودن. همه جا عالی تمیز شد.',
      customerTags: ['وقت‌شناس', 'کیفیت عالی', 'خوش‌برخورد', 'استفاده از تجهیزات کامل'],
      cleanerRating: 5,
      cleanerNotes: 'مشتری محترم و محیط کاری بسیار مرتب.',
      ratedAt: '2026-09-01T15:00:00.000Z',
    },
    createdAt: '2026-08-31T14:00:00.000Z',
    updatedAt: '2026-09-01T15:00:00.000Z',
  },
  {
    id: 'ORD-140306-085',
    orderNumber: 'پاکشو-۱۰۰۸۵',
    serviceId: 'staircase_common_areas',
    serviceTitle: 'نظافت راه‌پله و مشاعات',
    serviceSubtitle: 'قیمت‌گذاری کنتراتی و محاسباتی',
    pricingType: 'negotiable',
    status: 'CANCELLED',
    paymentStatus: 'FAILED',
    paymentMethod: 'ONLINE',
    date: {
      dateString: '1403-05-28',
      dayOfWeek: 'دوشنبه',
      dayOfMonth: 28,
      monthName: 'مرداد ۱۴۰۳',
      isToday: false,
    },
    timeSlot: {
      id: 'morning-1',
      startTime: '08:00',
      endTime: '10:00',
      label: 'صبح زود',
      period: 'MORNING',
      isAvailable: true,
    },
    durationHours: 3,
    genderPreference: 'MALE',
    serviceOptions: {
      floors: 5,
      parking: true,
      yard: true,
      glass: true,
    },
    recurringFrequency: 'MONTHLY',
    customerTier: 'GOLD',
    address: {
      district: 'پونک',
      fullAddress: 'بلوار همیلا، خیابان استاد نظری، پلاک ۱۸',
      plaque: '۱۸',
      unit: 'همکف',
      floor: 'همکف',
      hasElevator: true,
      contactPhone: '۰۹۱۲۳۴۵۶۷۸۹',
      recipientName: 'ساختمان یاس (آقای رضایی)',
      coordinates: { latitude: 35.7645, longitude: 51.3412 },
    },
    pricing: {
      subtotal: 580000,
      earlyBirdDiscountRate: 0,
      earlyBirdDiscountAmount: 0,
      tierDiscountRate: 0.05,
      tierDiscountAmount: 29000,
      recurringDiscountRate: 0.15,
      recurringDiscountAmount: 0,
      discountRate: 0.05,
      discountAmount: 29000,
      recurringDiscountDeferred: true,
      total: 551000,
    },
    timeline: [
      { step: 'SUBMITTED', title: 'ثبت سفارش', timestamp: '۲۸ مرداد', isCompleted: true, isCurrent: false },
      { step: 'CANCELLED', title: 'لغو سفارش', timestamp: '۲۸ مرداد', isCompleted: true, isCurrent: true, description: 'لغو به درخواست کاربر به دلیل تغییر زمان جلسه مجمع ساختمان' },
    ],
    notes: 'به دلیل هماهنگی دیرهنگام مدیر ساختمان لغو گردید.',
    createdAt: '2026-08-19T10:00:00.000Z',
    updatedAt: '2026-08-19T10:45:00.000Z',
  },
];
