import { CleaningService } from '../types/service';

export const SERVICES_CATALOG: CleaningService[] = [
  {
    id: 'home_unit_cleaning',
    title: 'نظافت داخل منزل / واحد',
    subtitle: 'خدمت ساعتی، حداقل ۴ ساعت',
    description: 'نظافت عمومی واحد با امکان انتخاب خدمات تکمیلی و نیروی خانم یا آقا.',
    iconName: 'home-outline',
    pricingType: 'hourly',
    basePrice: 150000,
    estimatedDurationHours: 4,
    badge: 'ساعتی',
    isVisible: true,
    configuration: {
      pricingLabel: 'ساعتی (حداقل ۴ ساعت)',
      includedOptions: ['دیوارشویی', 'شستشوی پنجره‌ها', 'اتوکشی / ظروف'],
      paidOptions: ['تهیه مواد شوینده'],
      inputs: [
        { id: 'gender', label: 'جنسیت متخصص', type: 'select', options: ['خانم', 'آقا'] },
        { id: 'detergent', label: 'تهیه مواد شوینده', type: 'boolean', price: 50000 },
      ],
    },
  },
  {
    id: 'staircase_common_areas',
    title: 'نظافت راه‌پله و مشاعات',
    subtitle: 'قیمت‌گذاری کنتراتی و محاسباتی',
    description: 'برآورد بر اساس طبقات، پارکینگ، حیاط و سن بنا.',
    iconName: 'building-outline',
    pricingType: 'negotiable',
    basePrice: 0,
    badge: 'کنتراتی',
    isVisible: true,
    configuration: {
      pricingLabel: 'کنتراتی و محاسباتی',
      paidOptions: ['شستشوی شیشه سکوریت'],
      inputs: [
        { id: 'floors', label: 'تعداد طبقات', type: 'number' },
        { id: 'parking', label: 'پارکینگ دارد؟', type: 'boolean' },
        { id: 'yard', label: 'حیاط دارد؟', type: 'boolean' },
        { id: 'buildingAge', label: 'سن بنا', type: 'select', options: ['نوساز تا ۱۰ سال', '۱۰ تا ۲۵ سال', 'بالای ۲۵ سال'] },
        { id: 'glass', label: 'شستشوی شیشه سکوریت', type: 'boolean', price: 150000 },
      ],
    },
  },
  {
    id: 'office_company_cleaning',
    title: 'نظافت دفاتر اداری و شرکت‌ها',
    subtitle: 'خدمت ساعتی، حداقل ۴ ساعت',
    description: 'نظافت منظم دفتر، اتاق‌ها و فضاهای عمومی شرکت.',
    iconName: 'briefcase-outline',
    pricingType: 'hourly',
    basePrice: 180000,
    estimatedDurationHours: 4,
    badge: 'سازمانی',
    isVisible: true,
    configuration: {
      pricingLabel: 'ساعتی (حداقل ۴ ساعت)',
      inputs: [{ id: 'hours', label: 'تعداد ساعت موردنیاز', type: 'number' }],
    },
  },
  {
    id: 'sofa_carpet_washing',
    title: 'مبل‌شویی و فرش‌شویی در محل',
    subtitle: 'قیمت‌گذاری بر اساس تعداد نشیمن و تشک',
    description: 'شستشوی مبلمان و فرش در محل با محاسبه تعداد نشیمن و تشک.',
    iconName: 'color-palette-outline',
    pricingType: 'count_based',
    basePrice: 350000,
    estimatedDurationHours: 3,
    badge: 'تعدادی',
    isVisible: true,
    configuration: {
      pricingLabel: 'بر اساس تعداد نشیمن مبل و تشک',
      inputs: [
        { id: 'sofaSeats', label: 'تعداد نشیمن مبل', type: 'select', options: ['۷ نفره', '۹ نفره'] },
        { id: 'mattresses', label: 'تعداد تشک', type: 'number' },
      ],
    },
  },
  {
    id: 'hourly_labor',
    title: 'کارگر ساعتی',
    subtitle: 'خدمت ساعتی، حداقل ۳ ساعت',
    description: 'نیروی کمکی ساعتی برای جابجایی اثاثیه، بارگیری، تخلیه انبار، کارهای سنگین و خدمات متفرقه.',
    iconName: 'hammer-outline',
    pricingType: 'hourly',
    basePrice: 120000,
    estimatedDurationHours: 3,
    badge: 'ساعتی',
    isVisible: true,
    configuration: {
      pricingLabel: 'ساعتی (حداقل ۳ ساعت)',
      includedOptions: ['جابجایی اثاثیه', 'بارگیری و تخلیه', 'کارهای سنگین'],
      paidOptions: ['ابزار و تجهیزات'],
      inputs: [
        { id: 'hours', label: 'تعداد ساعت مورد نیاز', type: 'number' },
        { id: 'workerCount', label: 'تعداد نیروی کارگر', type: 'select', options: ['۱ نفر', '۲ نفر', '۳ نفر'] },
        { id: 'tools', label: 'تهیه ابزار و تجهیزات', type: 'boolean', price: 80000 },
      ],
    },
  },
  {
    id: 'building_painting',
    title: 'نقاشی ساختمان',
    subtitle: 'قیمت‌گذاری بر اساس متراژ و نوع رنگ',
    description: 'نقاشی داخلی و خارجی ساختمان، منازل و دفاتر با ضمانت کیفیت رنگ و اجرا.',
    iconName: 'color-palette-outline',
    pricingType: 'per_sqm',
    basePrice: 85000,
    estimatedDurationHours: 8,
    badge: 'متراژی',
    isVisible: true,
    configuration: {
      pricingLabel: 'بر اساس متراژ (هر متر مربع)',
      includedOptions: ['آستری‌کشی', 'دو لایه رنگ', 'بتونه‌کاری سطحی'],
      paidOptions: ['تهیه رنگ', 'ابزار و وسایل', 'بتونه‌کاری کامل'],
      inputs: [
        { id: 'area', label: 'متراژ تقریبی (متر مربع)', type: 'number' },
        { id: 'paintType', label: 'نوع رنگ', type: 'select', options: ['رنگ معمولی', 'رنگ وینیل ضدآب', 'رنگ اپوکسی'] },
        { id: 'location', label: 'نوع فضا', type: 'select', options: ['داخلی', 'خارجی / نما'] },
        { id: 'providePaint', label: 'تهیه رنگ توسط پاکشو', type: 'boolean', price: 200000 },
        { id: 'fullPutty', label: 'بتونه‌کاری کامل دیوار', type: 'boolean', price: 150000 },
      ],
    },
  },
];
