import { CleaningService } from '../types/service';

export const SERVICES_CATALOG: CleaningService[] = [
  {
    id: 'general_cleaning',
    title: 'نظافت منزل و محل کار',
    subtitle: 'خدمت استاندارد',
    description: 'نظافت راه پله، سالن و اتاق‌ها با نیروهای آموزش‌دیده',
    iconName: 'home-outline',
    pricingType: 'hourly',
    basePrice: 150000,
    estimatedDurationHours: 4,
    badge: 'پرفروش',
    isVisible: true,
  },
  {
    id: 'sofa_washing',
    title: 'مبل‌شویی تخصصی در محل',
    subtitle: 'شستشوی مبلمان',
    description: 'شستشوی انواع مبلمان با دستگاه مکانیزه',
    iconName: 'color-palette-outline',
    pricingType: 'count_based',
    basePrice: 250000,
    estimatedDurationHours: 3,
    badge: 'در دسترس',
    isVisible: true,
  },
  {
    id: 'deep_cleaning',
    title: 'نظافت عمیق و تخصصی',
    subtitle: 'پاکیزگی عمیق',
    description: 'نظافت عمیق با مواد تخصصی برای منازل پس از تعمیرات یا اسباب‌کشی',
    iconName: 'sparkles',
    pricingType: 'hourly',
    basePrice: 220000,
    estimatedDurationHours: 5,
    badge: 'تخصصی',
    isVisible: true,
  },
  {
    id: 'end_of_tenant',
    title: 'نظافت پایان اجاره',
    subtitle: 'پاکسازی کامل',
    description: 'نظافت کامل و نهایی واحد برای تحویل به مالک یا مستأجر بعدی',
    iconName: 'home-outline',
    pricingType: 'fixed',
    basePrice: 850000,
    estimatedDurationHours: 8,
    badge: 'تخفیف',
    isVisible: true,
  },
  {
    id: 'office_cleaning',
    title: 'نظافت شرکت و دفتر کار',
    subtitle: 'خدمت سازمانی',
    description: 'نظافت منظم دفاتر، سالن‌ها و فضاهای عمومی شرکت‌ها',
    iconName: 'briefcase-outline',
    pricingType: 'hourly',
    basePrice: 180000,
    estimatedDurationHours: 4,
    badge: 'سازمانی',
    isVisible: true,
  },
  {
    id: 'construction_cleanup',
    title: 'پاکسازی پس از ساخت‌وساز',
    subtitle: 'پاکسازی تخصصی',
    description: 'پاکسازی گردوغبار و مواد باقی‌مانده پس از عملیات ساختمانی',
    iconName: 'hard-hat',
    pricingType: 'fixed',
    basePrice: 400000,
    estimatedDurationHours: 6,
    badge: 'تخصصی',
    isVisible: true,
  },
];
