import { CleaningService } from '../types/service';

export const SERVICES_CATALOG: CleaningService[] = [
  {
    id: 'home_unit_cleaning',
    title: 'نظافت داخل منزل / واحد',
    subtitle: 'خدمت ساعتی، حداقل ۴ ساعت',
    description: 'نظافت عمومی واحد با امکان انتخاب خدمات تکمیلی و نیروی خانم یا آقا.',
    iconName: 'home-outline',
    pricingType: 'hourly',
    basePrice: 150000,
    estimatedDurationHours: 4,
    badge: 'ساعتی',
    isVisible: true,
    configuration: {
      pricingLabel: 'ساعتی (حداقل ۴ ساعت)',
      includedOptions: ['دیوارشویی', 'شستشوی پنجره‌ها', 'اتوکشی / ظروف'],
      paidOptions: ['تهیه مواد شوینده'],
      inputs: [
        { id: 'gender', label: 'جنسیت متخصص', type: 'select', options: ['خانم', 'آقا'] },
        { id: 'detergent', label: 'تهیه مواد شوینده', type: 'boolean', price: 50000 },
      ],
    },
  },
  {
    id: 'staircase_common_areas',
    title: 'نظافت راه‌پله و مشاعات',
    subtitle: 'قیمت‌گذاری کنتراتی و محاسباتی',
    description: 'برآورد بر اساس طبقات، پارکینگ، حیاط و سن بنا.',
    iconName: 'building-outline',
    pricingType: 'negotiable',
    basePrice: 0,
    badge: 'کنتراتی',
    isVisible: true,
    configuration: {
      pricingLabel: 'کنتراتی و محاسباتی',
      paidOptions: ['شستشوی شیشه سکوریت'],
      inputs: [
        { id: 'floors', label: 'تعداد طبقات', type: 'number' },
        { id: 'parking', label: 'پارکینگ دارد؟', type: 'boolean' },
        { id: 'yard', label: 'حیاط دارد؟', type: 'boolean' },
        { id: 'buildingAge', label: 'سن بنا', type: 'select', options: ['نوساز تا ۱۰ سال', '۱۰ تا ۲۵ سال', 'بالای ۲۵ سال'] },
        { id: 'glass', label: 'شستشوی شیشه سکوریت', type: 'boolean', price: 150000 },
      ],
    },
  },
  {
    id: 'office_company_cleaning',
    title: 'نظافت دفاتر اداری و شرکت‌ها',
    subtitle: 'خدمت ساعتی، حداقل ۴ ساعت',
    description: 'نظافت منظم دفتر، اتاق‌ها و فضاهای عمومی شرکت.',
    iconName: 'briefcase-outline',
    pricingType: 'hourly',
    basePrice: 180000,
    estimatedDurationHours: 4,
    badge: 'سازمانی',
    isVisible: true,
    configuration: {
      pricingLabel: 'ساعتی (حداقل ۴ ساعت)',
      inputs: [{ id: 'hours', label: 'تعداد ساعت موردنیاز', type: 'number' }],
    },
  },
  {
    id: 'sofa_carpet_washing',
    title: 'مبل‌شویی و فرش‌شویی در محل',
    subtitle: 'قیمت‌گذاری بر اساس تعداد نشیمن و تشک',
    description: 'شستشوی مبلمان و فرش در محل با محاسبه تعداد نشیمن و تشک.',
    iconName: 'color-palette-outline',
    pricingType: 'count_based',
    basePrice: 350000,
    estimatedDurationHours: 3,
    badge: 'تعدادی',
    isVisible: true,
    configuration: {
      pricingLabel: 'بر اساس تعداد نشیمن مبل و تشک',
      inputs: [
        { id: 'sofaSeats', label: 'تعداد نشیمن مبل', type: 'select', options: ['۷ نفره', '۹ نفره'] },
        { id: 'mattresses', label: 'تعداد تشک', type: 'number' },
      ],
    },
  },
];
